# -*- mode: python -*-

block_cipher = None


a = Analysis(['ddb/cli.py'],
             pathex=['.'],
             binaries=[
                 ('./ddb/__init__.py', '.'), 
                 ('./ddb/version.so', '.'),
                 ('./ddb/sql_engine.so', '.'), 
                 ('./ddb/interactive.so', '.'),
                 ('./ddb/lexer/sql_tokenize.so', 'lexer'), 
                 ('./ddb/lexer/__init__.py', 'lexer'), 
                 ('./ddb/lexer/sql_parser.so', 'lexer'), 
                 ('./ddb/lexer/language.so', 'lexer'), 
                 ('./ddb/evaluate/match.so', 'evaluate'), 
                 ('./ddb/evaluate/__init__.py', 'evaluate'), 
                 ('./ddb/functions/functions.so', 'functions'), 
                 ('./ddb/functions/__init__.py', 'functions'), 
                 ('./ddb/structure/__init__.py', 'structure'), 
                 ('./ddb/structure/table.so', 'structure'), 
                 ('./ddb/structure/column.so', 'structure'), 
                 ('./ddb/output/__init__.py', 'output'), 
                 ('./ddb/output/factory.so', 'output'), 
                 ('./ddb/output/factory_xml.so', 'output'), 
                 ('./ddb/output/factory_json.so', 'output'), 
                 ('./ddb/output/factory_yaml.so', 'output'), 
                 ('./ddb/structure/database.so', 'structure'), ],
             datas=[],
             hiddenimports=['nt', 'os2', 'ce', 'riscos', 'riscospath', 'riscosenviron', 'msvcrt', 'subprocess',  'flextable'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='ddb',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
