
sql_syntax={
    'functions':[ {'name':'database','arguments':None},
                {'name':'count','arguments':[{'name':'where','required':True}]},
                {'name':'sum','arguments':[{'name':'column','required':True}]}
                ],
    'query_matrix':[
                    {'query': 'show tables',
                    'switch': [{'data': False, 'name': ['show', 'tables']}]},
                    {'query': 'show columns',
                    'switch': [{'data': False, 'name': ['show', 'columns']},
                                {'arguments': 1,
                                'data': [{'sig': ['{table}']}],
                                'name': 'from'}]},
                    {'argument': 1,
                    'query': 'select',
                    'switch': [{'arguments': 0,
                                'data': [{'sig': ['{column}']},
                                            {'sig': ['{column}',
                                                        'as',
                                                        '{display}']},
                                            {'sig': ['{function}',
                                                    '(',
                                                    ')']},
                                            {'sig': ['{function}',
                                                    '(',
                                                    '{argument1}',
                                                    ')'
                                                    ]},
                                            {'sig': ['{function}',
                                                    '(',
                                                    '{argument1}',
                                                    ',',
                                                    '{argument2}',
                                                    ')'
                                                    ]},
                                            {'sig': ['{function}',
                                                    '(',
                                                    '{argument1}',
                                                    ',',
                                                    '{argument2}',
                                                    ',',
                                                    '{argument3}',
                                                    ')'
                                                    ]},
                                            {'sig': ['{function}',
                                                    '(',
                                                    ')',
                                                    'as',
                                                    '{display}'
                                                    ]},
                                            {'sig': ['{function}',
                                                    '(',
                                                    '{argument1}',
                                                    ')',
                                                    'as',
                                                    '{display}'
                                                    ]},
                                            {'sig': ['{function}',
                                                    '(',
                                                    '{argument1}',
                                                    ',',
                                                    '{argument2}',
                                                    ')',
                                                    'as',
                                                    '{display}'
                                                    ]},
                                            {'sig': ['{function}',
                                                    '(',
                                                    '{argument1}',
                                                    ',',
                                                    '{argument2}',
                                                    ',',
                                                    '{argument3}',
                                                    ')',
                                                    'as',
                                                    '{display}'
                                                    ]},

                                                    ],
                                'name': 'select'},
                                {'arguments': 1,
                                'data': [{'sig': ['{table}']}],
                                'name': 'from'},
                                {'arguments': 1,
                                'data': [{'sig': ['{e1}', '{c}', '{e2}']}],
                                'name': 'where',
                                'optional': True,
                                'store_array': True},
                                {'arguments': 1,
                                'data': [{'sig': ['{e1}', '{c}', '{e2}']}],
                                'depends_on': 'where',
                                'jump': 'where',
                                'name': 'and',
                                'optional': True,
                                'parent': 'where'},
                                {'arguments': 1,
                                'data': [{'sig': ['{e1}', '{c}', '{e2}']}],
                                'depends_on': 'where',
                                'jump': 'where',
                                'name': 'or',
                                'optional': True,
                                'parent': 'where'},
                                {'arguments': 0,
                                'data': [{'sig': ['{column}']},
                                            {'sig': ['{column}', 'asc']},
                                            {'sig': ['{column}', 'desc']}],
                                'name': ['order', 'by'],
                                'optional': True},
                                {'data': [{'sig': ['{#length}']},
                                            {'sig': ['{#start}',
                                                    ',',
                                                    '{#length}']}],
                                'name': 'limit',
                                'optional': True}]},
                    {'query': 'delete',
                    'switch': [{'data': False, 'name': 'delete'},
                                {'arguments': 1,
                                'data': [{'sig': ['{table}']}],
                                'name': 'from'},
                                {'arguments': 1,
                                'data': [{'sig': ['{e1}', '{c}', '{e2}']}],
                                'name': 'where',
                                'optional': True,
                                'store_array': True},
                                {'arguments': 0,
                                'data': [{'sig': ['{e1}', '{c}', '{e2}']}],
                                'depends_on': 'where',
                                'jump': 'where',
                                'name': 'and',
                                'optional': True,
                                'parent': 'where'},
                                {'arguments': 1,
                                'data': [{'sig': ['{e1}', '{c}', '{e2}']}],
                                'depends_on': 'where',
                                'jump': 'where',
                                'name': 'or',
                                'optional': True,
                                'parent': 'where'}]},
                    {'query': 'insert',
                    'switch': [{'data': False, 'name': 'insert'},
                                {'arguments': 1,
                                'data': [{'sig': ['{table}']}],
                                'name': 'into'},
                                {'data': False, 'dispose': True, 'name': '('},
                                {'arguments': 0,
                                'data': [{'sig': ['{column}']}],
                                'name': 'columns',
                                'no_keyword': True},
                                {'data': False, 'dispose': True, 'name': ')'},
                                {'data': False,
                                'dispose': True,
                                'name': 'values'},
                                {'data': False, 'dispose': True, 'name': '('},
                                {'arguments': 0,
                                'data': [{'sig': ['{value}']}],
                                'name': 'values',
                                'no_keyword': True},
                                {'data': False, 'dispose': True, 'name': ')'}]},
                    {'query': 'update',
                    'switch': [{'arguments': 1,
                                'data': [{'sig': ['{table}']}],
                                'name': 'update'},
                                {'arguments': 0,
                                'data': [{'sig': ['{column}', '=', '{e}']}],
                                'name': 'set'},
                                {'arguments': 1,
                                'data': [{'sig': ['{e1}', '{c}', '{e2}']}],
                                'name': 'where',
                                'optional': True,
                                'store_array': True},
                                {'arguments': 0,
                                'data': [{'sig': ['{e1}', '{c}', '{e2}']}],
                                'depends_on': 'where',
                                'jump': 'where',
                                'name': 'and',
                                'optional': True,
                                'parent': 'where'},
                                {'arguments': 1,
                                'data': [{'sig': ['{e1}', '{c}', '{e2}']}],
                                'depends_on': 'where',
                                'jump': 'where',
                                'name': 'or',
                                'optional': True,
                                'parent': 'where'}]},
                    {'query': 'use',
                    'switch': [{'arguments': 1,
                                'data': [{'sig': ['{table}']}],
                                'name': 'use'}]},
                    {'query': 'drop table',
                    'switch': [{'arguments': 1,
                                'data': [{'sig': ['table', '{table}']}],
                                'name': 'drop'}]},
                    {'query': 'create table',
                    'switch': [{'arguments': 1,
                                'data': [{'sig': ['table', '{table}']}],
                                'name': 'create'},
                                {'data': False, 'dispose': True, 'name': '('},
                                {'arguments': 0,
                                'data': [{'sig': ['{column}']}],
                                'name': 'columns',
                                'no_keyword': True},
                                {'data': False, 'dispose': True, 'name': ')'},
                                {'arguments': 1,
                                'data': [{'sig': ['=', '{file}']}],
                                'name': 'file'}]}]
}