query_matrix=  [{'query': 'show tables',
                   'switch': [{'data': False, 'name': ['show', 'tables']}]},
                  {'query': 'show columns',
                   'switch': [{'data': False, 'name': ['show', 'columns']},
                              {'arguments': 1,
                               'data': [{'sig': ['{table}']}],
                               'name': 'from'}]},
                  {'argument': 1,
                   'query': 'select',
                   'switch': [{'arguments': 0,
                               'data': [{'sig': ['{column}']},
                                        {'sig': ['{column}',
                                                 'as',
                                                 '{display}']}],
                               'name': 'select'},
                              {'arguments': 1,
                               'data': [{'sig': ['{table}']}],
                               'name': 'from'},
                              {'arguments': 1,
                               'data': [{'sig': ['{expression1}',
                                                 '{condition}',
                                                 '{expression2}']}],
                               'name': 'where',
                               'optional': True,
                               'store_array': True},
                              {'arguments': 1,
                               'data': [{'sig': ['{expression1}',
                                                 '{condition}',
                                                 '{expression2}']}],
                               'depends_on': 'where',
                               'jump': 'where',
                               'name': 'and',
                               'optional': True,
                               'parent': 'where'},
                              {'arguments': 1,
                               'data': [{'sig': ['{expression1}',
                                                 '{condition}',
                                                 '{expression2}']}],
                               'depends_on': 'where',
                               'jump': 'where',
                               'name': 'or',
                               'optional': True,
                               'parent': 'where'},
                              {'arguments': 0,
                               'data': [{'sig': ['{column}']},
                                        {'sig': ['{column}', 'asc']},
                                        {'sig': ['{column}', 'desc']}],
                               'name': ['order', 'by'],
                               'optional': True},
                              {'data': [{'sig': ['{#length}']},
                                        {'sig': ['{#start}',
                                                 ',',
                                                 '{#length}']}],
                               'name': 'limit',
                               'optional': True}]},
                  {'query': 'delete',
                   'switch': [{'data': False, 'name': 'delete'},
                              {'arguments': 1,
                               'data': [{'sig': ['{table}']}],
                               'name': 'from'},
                              {'arguments': 1,
                               'data': [{'sig': ['{expression1}',
                                                 '{condition}',
                                                 '{expression2}']}],
                               'name': 'where',
                               'optional': True,
                               'store_array': True},
                              {'arguments': 0,
                               'data': [{'sig': ['{expression1}',
                                                 '{condition}',
                                                 '{expression2}']}],
                               'depends_on': 'where',
                               'jump': 'where',
                               'name': 'and',
                               'optional': True,
                               'parent': 'where'},
                              {'arguments': 1,
                               'data': [{'sig': ['{expression1}',
                                                 '{condition}',
                                                 '{expression2}']}],
                               'depends_on': 'where',
                               'jump': 'where',
                               'name': 'or',
                               'optional': True,
                               'parent': 'where'}]},
                  {'query': 'insert',
                   'switch': [{'data': False, 'name': 'insert'},
                              {'arguments': 1,
                               'data': [{'sig': ['{table}']}],
                               'name': 'into'},
                              {'data': False, 'dispose': True, 'name': '('},
                              {'arguments': 0,
                               'data': [{'sig': ['{column}']}],
                               'name': 'columns',
                               'no_keyword': True},
                              {'data': False, 'dispose': True, 'name': ')'},
                              {'data': False,
                               'dispose': True,
                               'name': 'values'},
                              {'data': False, 'dispose': True, 'name': '('},
                              {'arguments': 0,
                               'data': [{'sig': ['{value}']}],
                               'name': 'values',
                               'no_keyword': True},
                              {'data': False, 'dispose': True, 'name': ')'}]},
                  {'query': 'update',
                   'switch': [{'arguments': 1,
                               'data': [{'sig': ['{table}']}],
                               'name': 'update'},
                              {'arguments': 0,
                               'data': [{'sig': ['{column}',
                                                 '=',
                                                 '{expression}']}],
                               'name': 'set'},
                              {'arguments': 1,
                               'data': [{'sig': ['{expression1}',
                                                 '{condition}',
                                                 '{expression2}']}],
                               'name': 'where',
                               'optional': True,
                               'store_array': True},
                              {'arguments': 0,
                               'data': [{'sig': ['{expression1}',
                                                 '{condition}',
                                                 '{expression2}']}],
                               'depends_on': 'where',
                               'jump': 'where',
                               'name': 'and',
                               'optional': True,
                               'parent': 'where'},
                              {'arguments': 1,
                               'data': [{'sig': ['{expression1}',
                                                 '{condition}',
                                                 '{expression2}']}],
                               'depends_on': 'where',
                               'jump': 'where',
                               'name': 'or',
                               'optional': True,
                               'parent': 'where'}]}]